Models/Comment.cs
using CSharp___WebBlog.Enums;
using Microsoft.AspNetCore.Identity;
using System;
using System.ComponentModel.DataAnnotations;

namespace CSharp___WebBlog.Models
{
    public class Comment
    {
        public int Id { get; set; }
        public int PostId { get; set; } // Foreign key
        public string BlogUserId { get; set; }
        public string ModeratorId { get; set; }

        [Required]
        [StringLength(500, ErrorMessage = "The {0} must be at least {2} and at most {1} characters long.", MinimumLength = 2)]
        [Display(Name = "(500 characters or less)")]
        public string Body { get; set; }

        [DataType(DataType.Date)]
        public DateTime Created { get; set; }

        public DateTime? Updated { get; set; } //Nullable b/c someone may NOT have updated
        public DateTime? Moderated { get; set; }
        public DateTime? Deleted { get; set; }

        [StringLength(500, ErrorMessage = "The {0} must be at least {2} and at most {1} characters long.", MinimumLength = 2)]
        [Display(Name = "Moderated Comment")]
        public string ModeratedBody { get; set; }

        public ModerationType ModerationType { get; set; }

        //Navigation Properties - that reference the parent => no ICollection
        public virtual Post Post { get; set; }

        public virtual BlogUser BlogUser { get; set; }
        public virtual BlogUser Moderator { get; set; }
    }
}

Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CSharp___WebBlog.Data;
using CSharp___WebBlog.Models;

namespace CSharp___WebBlog.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CommentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Comments - The original Index
        public async Task<IActionResult> OriginalIndex()
        {
            var originalComments = await _context.Comments.ToListAsync();
            return View("Index", originalComments);
        }

        public async Task<IActionResult> ModeratedIndex()
        {
            var originalComments = await _context.Comments.Where(c => c.Moderated != null).ToListAsync();
            return View("Index", originalComments);
        }

        public async Task<IActionResult> DeletedIndex()
        {
            //eager loading of data (Include...)
            var originalComments = await _context.Comments.Include(c => c.BlogUser).Include(c => c.Moderator).Include(c => c.Post).Where(c => c.Deleted != null).ToListAsync();
            return View("Index", originalComments);
        }

        public async Task<IActionResult> Index()
        {
            var allComments = await _context.Comments.ToListAsync();
            return View(allComments);
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.BlogUser)
                .Include(c => c.Moderator)
                .Include(c => c.Post)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create (does not get used)
        //public IActionResult Create()
        //{
        //    ViewData["BlogUserId"] = new SelectList(_context.Users, "Id", "Id");
        //    ViewData["ModeratorId"] = new SelectList(_context.Users, "Id", "Id");
        //    ViewData["PostId"] = new SelectList(_context.Posts, "Id", "Abstract");
        //    return View();
        //}

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PostId,BlogUserId,ModeratorId,Body,Created,Updated,Moderated,Deleted,ModeratedBody,ModerationType")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BlogUserId"] = new SelectList(_context.Users, "Id", "Id", comment.BlogUserId);
            ViewData["ModeratorId"] = new SelectList(_context.Users, "Id", "Id", comment.ModeratorId);
            ViewData["PostId"] = new SelectList(_context.Posts, "Id", "Abstract", comment.PostId);
            return View(comment);
        }

        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            ViewData["BlogUserId"] = new SelectList(_context.Users, "Id", "Id", comment.BlogUserId);
            ViewData["ModeratorId"] = new SelectList(_context.Users, "Id", "Id", comment.ModeratorId);
            ViewData["PostId"] = new SelectList(_context.Posts, "Id", "Abstract", comment.PostId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PostId,BlogUserId,ModeratorId,Body,Created,Updated,Moderated,Deleted,ModeratedBody,ModerationType")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["BlogUserId"] = new SelectList(_context.Users, "Id", "Id", comment.BlogUserId);
            ViewData["ModeratorId"] = new SelectList(_context.Users, "Id", "Id", comment.ModeratorId);
            ViewData["PostId"] = new SelectList(_context.Posts, "Id", "Abstract", comment.PostId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.BlogUser)
                .Include(c => c.Moderator)
                .Include(c => c.Post)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comment = await _context.Comments.FindAsync(id);
            _context.Comments.Remove(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommentExists(int id)
        {
            return _context.Comments.Any(e => e.Id == id);
        }
    }
}

Views/Comments/Create.cshtml
@model CSharp___WebBlog.Models.Comment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Comment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PostId" class="control-label"></label>
                <select asp-for="PostId" class ="form-control" asp-items="ViewBag.PostId"></select>
            </div>
            <div class="form-group">
                <label asp-for="BlogUserId" class="control-label"></label>
                <select asp-for="BlogUserId" class ="form-control" asp-items="ViewBag.BlogUserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ModeratorId" class="control-label"></label>
                <select asp-for="ModeratorId" class ="form-control" asp-items="ViewBag.ModeratorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Updated" class="control-label"></label>
                <input asp-for="Updated" class="form-control" />
                <span asp-validation-for="Updated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Moderated" class="control-label"></label>
                <input asp-for="Moderated" class="form-control" />
                <span asp-validation-for="Moderated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deleted" class="control-label"></label>
                <input asp-for="Deleted" class="form-control" />
                <span asp-validation-for="Deleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModeratedBody" class="control-label"></label>
                <input asp-for="ModeratedBody" class="form-control" />
                <span asp-validation-for="ModeratedBody" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModerationType" class="control-label"></label>
                <select asp-for="ModerationType" class="form-control"></select>
                <span asp-validation-for="ModerationType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Comments/Delete.cshtml
@model CSharp___WebBlog.Models.Comment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Comment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Updated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Updated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Moderated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Moderated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModeratedBody)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModeratedBody)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModerationType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModerationType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Post)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Post.Abstract)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BlogUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BlogUser.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Moderator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Moderator.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Comments/Details.cshtml
@model CSharp___WebBlog.Models.Comment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Comment</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Updated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Updated)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Moderated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Moderated)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Deleted)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModeratedBody)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModeratedBody)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModerationType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModerationType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Post)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Post.Abstract)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BlogUser)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BlogUser.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Moderator)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Moderator.Id)
        </dd>
    </dl>
</div>
<form asp-controller="Comments" asp-action="Create">
</form>

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Comments/Edit.cshtml
@model CSharp___WebBlog.Models.Comment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Comment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PostId" class="control-label"></label>
                <select asp-for="PostId" class="form-control" asp-items="ViewBag.PostId"></select>
                <span asp-validation-for="PostId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogUserId" class="control-label"></label>
                <select asp-for="BlogUserId" class="form-control" asp-items="ViewBag.BlogUserId"></select>
                <span asp-validation-for="BlogUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModeratorId" class="control-label"></label>
                <select asp-for="ModeratorId" class="form-control" asp-items="ViewBag.ModeratorId"></select>
                <span asp-validation-for="ModeratorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Updated" class="control-label"></label>
                <input asp-for="Updated" class="form-control" />
                <span asp-validation-for="Updated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Moderated" class="control-label"></label>
                <input asp-for="Moderated" class="form-control" />
                <span asp-validation-for="Moderated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deleted" class="control-label"></label>
                <input asp-for="Deleted" class="form-control" />
                <span asp-validation-for="Deleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModeratedBody" class="control-label"></label>
                <input asp-for="ModeratedBody" class="form-control" />
                <span asp-validation-for="ModeratedBody" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModerationType" class="control-label"></label>
                <select asp-for="ModerationType" class="form-control"></select>
                <span asp-validation-for="ModerationType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Comments/Index.cshtml
@model IEnumerable<CSharp___WebBlog.Models.Comment>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Body)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Updated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Moderated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModeratedBody)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModerationType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Post)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BlogUser)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Moderator)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Updated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Moderated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModeratedBody)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModerationType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Post.Abstract)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BlogUser.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Moderator.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>